# Generated by Django 5.0.3 on 2024-03-31 17:23

import RSS_Sources.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RSS_Sources', '0005_rss_cache_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('source', models.ForeignKey(default=RSS_Sources.models.Source.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='RSS_Sources.source')),
            ],
        ),
    ]
