# Generated by Django 5.0.3 on 2024-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_content_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
