# Generated by Django 5.0.3 on 2024-03-30 20:36

import RSS_Sources.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('source_type', models.CharField(choices=[('Video', 'Video'), ('audio_pod', 'Audio Podcast'), ('video_pod', 'Video Podcast'), ('text', 'Text Article'), ('smp', 'Social Media Post'), ('oth', 'Others')], default='oth', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('favicon', models.CharField(max_length=2048, null=True)),
                ('rss_feed_link', models.CharField(max_length=4096)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('type', models.ForeignKey(default=RSS_Sources.models.SourceType.get_default_pk, on_delete=django.db.models.deletion.RESTRICT, to='RSS_Sources.sourcetype')),
            ],
        ),
    ]
