# Generated by Django 5.0.3 on 2024-03-30 20:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS_Sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='favicon',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
