# Generated by Django 5.0.3 on 2024-03-31 09:37

import RSS_Sources.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS_Sources', '0002_alter_source_favicon_alter_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSS_Cache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(default=RSS_Sources.models.Source.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='RSS_Sources.source')),
            ],
        ),
    ]
