# Generated by Django 5.0.3 on 2024-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS_Sources', '0003_rss_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rss_cache',
            options={'verbose_name': 'RSS Cache', 'verbose_name_plural': 'RSS Cache'},
        ),
        migrations.AddField(
            model_name='source',
            name='update_interval',
            field=models.IntegerField(default=10),
        ),
    ]
