# Generated by Django 5.0.3 on 2024-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS_Sources', '0004_alter_rss_cache_options_source_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss_cache',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
